badge_typo_dict = {
 "Asstronomy": "Astronomy",
 "Chem": "Chemistry",
 "Chemsitry": "Chemistry",
 "Cit Comm": "Cit Community",
 "Cit Wolrd": "Cit World",
 "Cit in Community": "Cit Community",
 "Cit in Nation": "Cit Nation",
 "Cit nation": "Cit Nation",
 "Cit world": "Cit World",
 "Citizenship World": "Cit World",
 "Citizenship in the Community": "Cit Community",
 "Citizenship in the Nation": "Cit Nation",
 "Citizenship in the World": "Cit World",
 "Citizenship of the World": "Cit World",
 "Citzenship in the Nation": "Cit Nation",
 "Communication": "Communications",
 "Dig Tech": "Ditital Technology",
 "Digital Tech": "Digital Technology",
 "Digital Technology (not offered at time)": "Digital Technology",
 "Em Prep": "E Prep",
 "Em prep": "E Prep",
 "Emergency Prep": "E Prep",
 "Emergency Prepardness": "E Prep",
 "Emergency Preparedness": "E Prep",
 "Eng": "Engineering",
 "Engineeringineering": "Engineering",
 "Env science": "E Sci",
 "Enviornmental Science": "E Sci",
 "Environmental Science": "E Sci",
 "Environmental science": "E Sci",
 "Evironmental Science": "E Sci",
 "First aid": "First Aid",
 "Game Design": "Game Design",
 "Music ": "Music",
 "Photo": "Photography",
 "Programing": "Programming",
 "Progreamming": "Programming",
 "Sales": "American Business",
 "Salesmanship": "American Business",
 "Salesmenship": "American Business",
 "Soil and Water Conservation": "Soil/Water Cons",
 "Soil/Water": "Soil/Water Cons",
 "Space Exploration": "Space Ex",
 "SpaceX": "Space Ex",
 "chess": "Chess",
 "cit in comm": "Cit Community",
 "cit in world": "Cit World",
 "comm": "Communications",
 "communications": "Communications",
 "digital Technology": "Digital Technology",
 "e prep": "E Prep",
 "e sci": "E Sci",
 "electronics": "Electronics",
 "energy": "Energy",
 "engineering": "Engineering",
 "first aid": "First Aid",
}